apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
  labels:
    app: basic-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: basic-app 