replicaCount: 1

image:
  repository: 010438464212.dkr.ecr.ap-northeast-2.amazonaws.com/aic-demo-api
  tag: latest
  pullPolicy: ifNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}


